{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lenebf.plugin",
    "module": "apk-rename",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "wcjl5upv6vf7nd5ar22qnzrjru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "apk-rename-0.0.6.jar",
          "url": "apk-rename-0.0.6.jar",
          "size": 6835,
          "sha512": "d54b5927cc0caf0581b37b752c749dc7dbf01d1674b9e62258ed9002005c1122594f6694c92029472b72a6cbe695a364f68e9a16a8c3c543e3349535a13a7904",
          "sha256": "45ec4c5b1da8d14306c7d61da751b7aebd169947757928034292ec37bceaa75f",
          "sha1": "26a3d778d63e1a95f979eb69dc8d27f7c304a707",
          "md5": "79b717657d0ba8b732eaa0f2d00606a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "apk-rename-0.0.6.jar",
          "url": "apk-rename-0.0.6.jar",
          "size": 6835,
          "sha512": "d54b5927cc0caf0581b37b752c749dc7dbf01d1674b9e62258ed9002005c1122594f6694c92029472b72a6cbe695a364f68e9a16a8c3c543e3349535a13a7904",
          "sha256": "45ec4c5b1da8d14306c7d61da751b7aebd169947757928034292ec37bceaa75f",
          "sha1": "26a3d778d63e1a95f979eb69dc8d27f7c304a707",
          "md5": "79b717657d0ba8b732eaa0f2d00606a3"
        }
      ]
    }
  ]
}
